# Generated by Django 3.0.8 on 2020-07-12 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='email',
            field=models.EmailField(default='sinejemplo@hotmail.com', max_length=254),
        ),
    ]
