# Generated by Django 3.0.8 on 2020-07-19 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_profesor_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('apellido', models.CharField(max_length=120)),
                ('rut', models.IntegerField()),
                ('email', models.EmailField(default='sinejemplo@hotmail.com', max_length=254)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrc', models.IntegerField()),
                ('semestre', models.TextField()),
                ('codigo_curso', models.IntegerField()),
                ('usuariounab', models.TextField()),
            ],
        ),
    ]
