# Generated by Django 3.0.8 on 2020-07-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_estudiante_seccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdEjercicio', models.CharField(max_length=20)),
                ('nombreProblema', models.CharField(max_length=20)),
                ('skill1', models.BooleanField()),
                ('skill2', models.BooleanField()),
                ('skill3', models.BooleanField()),
                ('skill4', models.BooleanField()),
                ('knowledge1', models.NullBooleanField()),
                ('knowledge2', models.NullBooleanField()),
                ('knowledge3', models.NullBooleanField()),
                ('knowledge4', models.NullBooleanField()),
                ('complejidad', models.CharField(max_length=20)),
                ('hito', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrc', models.CharField(max_length=20)),
                ('email', models.EmailField(default='sinejemplo@hotmail.com', max_length=254)),
                ('notas', models.DecimalField(decimal_places=3, max_digits=20)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ramo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoRamo', models.CharField(max_length=20)),
                ('nombreRamo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TablonEjercicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20)),
                ('nrc', models.CharField(max_length=20)),
                ('email', models.EmailField(default='sinejemplo@hotmail.com', max_length=254)),
                ('dia', models.CharField(max_length=20)),
                ('mes', models.CharField(max_length=20)),
                ('año', models.CharField(max_length=20)),
                ('idEjercicio', models.CharField(max_length=20)),
                ('nombreProblema', models.CharField(max_length=20)),
                ('puntaje', models.DecimalField(decimal_places=3, max_digits=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='seccion',
            name='usuariounab',
        ),
        migrations.AddField(
            model_name='seccion',
            name='email',
            field=models.EmailField(default='sinejemplo@hotmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='rut',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='rut',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='nrc',
            field=models.CharField(max_length=20),
        ),
    ]
